FROM node:18 AS build
WORKDIR /app
COPY ./front-end/package*.json ./
RUN npm ci --omit=dev
COPY ./front-end .
RUN npm run build

FROM nginx:1.25-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80