
# =============================
# Docker Swarm Stack para produção
# =============================
version: '3.8'


services:
  # Front-end React (build estático)
  front-end:
    image: kayquews/site-frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - site-network

  # Back-end Node.js (API)
  back-end:
    image: kayquews/site-backend:latest
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - PORT=5000
    # Não expõe porta diretamente, só via nginx
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - site-network

  # Nginx reverso (único ponto de entrada)
  nginx:
    image: kayquews/site-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - site-network


# Rede overlay para comunicação entre serviços
networks:
  site-network:
    driver: overlay
