version: '3.8'

services:
  front-end:
    image: username/site-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - site-network

  back-end:
    image: username/site-backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - site-network

  nginx:
    image: username/site-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - site-network

networks:
  site-network:
    driver: overlay
